services:

  db:
    image: mysql
    restart: always
    volumes:
      - db-recruit:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
    networks:
      - recruit-net
  
  recruit:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      .env
    environment:
      - MYSQL_HOST='db'
      - MYSQL_PORT=3306
    depends_on:
      - db
    networks:
      - recruit-net

volumes:
  db-recruit:

networks:
  recruit-net:
  