services:

  db:
    image: mysql
    restart: always
    volumes:
      - db-recruit:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DBNAME}
  
  recruit:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      - db

volumes:
  db-recruit:
  