name: test and depoly
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MYSQL_DBNAME: 'recruit'
      MYSQL_PASSWORD: '1234'
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_AUTH: ${{ secrets.EMAIL_AUTH }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DBNAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=3s --health-timeout=5s --health-retries=3
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: setup environment
        run: pip install -r requirements.txt
      
      - name: run test
        run: pytest
      
  merge_and_deploy:
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: merge
        run: |
          git config user.name lllei
          git config user.email llleigoing@outlook.com
          git checkout main
          git merge dev
          git push
      
      - name: depoly
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: lllei.top
          REMOTE_USER: lllei
          SOURCE: 'app requirements.txt'
          ARGS: "-rlgoDzvc -i --delete"
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            cd ${{ secrets.REMOTE_TARGET }} 
            docker compose build recruit
            docker compose up --no-deps -d recruit